version: "3.7"
services:

## Starts up mySQL server for ubyssey.ca and Dispatch
  db:
    image: mysql:5.7
    volumes:
      - database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ubyssey
      MYSQL_USER: root
      MYSQL_PASSWORD: ubyssey
      MYSQL_DATABASE: ubyssey
    ports:
      - "3307:3306"
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=ubyssey --execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 20

## Starts up Django server for ubyssey.ca
  django:
    image: ubyssey/ubyssey.ca:latest
    volumes:
      - ..:/workspaces/mount
      - .:/workspaces/ubyssey.ca/tmp
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.development
      GOOGLE_APPLICATION_CREDENTIALS: somecredentials
    ports:
      - "8000:8000"
      - "4444:4444"
    depends_on:
      - db
    stdin_open: true
    tty: true
    
## Static filewatcher
  filewatcher:
    image: ubyssey/ubyssey-watcher:latest
    volumes:
      - ../ubyssey.ca/ubyssey/static/src:/src
    depends_on:
      - django
    
volumes:
  database:
    external:
      name: ubyssey_db_volume