version: "3.7"
services:
  selenium-chrome:
    image: selenium/standalone-chrome
    ports:
      - 4444:4444
      - 5900:5900 
  selenium-edge:
    image: selenium/standalone-edge
    ports:
      - 4445:4444 
      - 5901:5900 

  selenium-firefox:
    image: selenium/standalone-firefox
    ports:
      - 4446:4444 
      - 5902:5900 

## Starts up mySQL server for ubyssey.ca and Dispatch
  db:
    platform: linux/x86_64
    image: mysql:5.7
    volumes:
      - database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ubyssey
      MYSQL_DATABASE: ubyssey
    ports:
      - "3307:3306"
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=ubyssey --execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 20

## Starts up Django server for ubyssey.ca
  django:
    image: ubyssey/ubyssey.ca:latest
    volumes:
      - ..:/workspaces/mount
      - .:/workspaces/ubyssey.ca/tmp
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.development
    #ports:
      # # If you uncomment these, it will enable port TUNNELLING for the container
      # # Allocation of port tunnel can conflict with port forwarding! If you have issues make sure you're only using one or the other!
    #  - "8000:8000"
    #  - "4444:4444"
    depends_on:
      - db
    stdin_open: true
    tty: true
    links:
      - selenium-chrome
      - selenium-edge 
      - selenium-firefox
    
# ## Static filewatcher
  # filewatcher:
    # image: ubyssey/ubyssey-watcher:latest
    # volumes:
      # - ../ubyssey.ca/ubyssey/static/src:/src
    # depends_on:
      # - django
## 
  cache:
    platform: linux/x86_64
    image: memcached:1.6.10
    ports:
      - "11211:11211"
    depends_on:
      - django
    
volumes:
  database:
    external:
      name: ubyssey_db_volume
  
